apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: eventlog-fetch-job
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  schedule: "* * * * *"  # This will run the job every minute
  image: cgr.dev/chainguard/curl:latest
#  accessPolicy:
#    outbound:
#      rules:
#        - application: sf-eventlog
  command:
    - curl
    - http://sf-eventlog/internal/test
  restartPolicy: Never