apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: eventlog-fetch-job
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  schedule: "30 12 * * *"  # This will run the job every day at 12:00 PM UTC (1:00 PM CET)
  image: cgr.dev/chainguard/curl:latest
  accessPolicy:
    outbound:
      rules:
        - application: sf-eventlog
  command:
    - curl
    - http://sf-eventlog/internal/fetchAndLogYesterday
  restartPolicy: Never