apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-eventlog
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: sf-eventlog-dev
  ingresses:
    - "https://sf-eventlog.intern.dev.nav.no"
#  azure:
#    application:
#      enabled: true
#      allowAllUsers: true
#      tenant: trygdeetaten.no
#      claims:
#        extra:
#          - azp_name
#          - NAVident
#    sidecar:
#      enabled: false
#  accessPolicy:
#    inbound:
#      rules:
#        - application: salesforce
#          namespace: teamcrm
#          cluster: dev-external
  envFrom:
    - secret: sf-pubsub-preprod
  env:
    - name: SALESFORCE_API_VERSION
      value: "v58.0"
    - name: CONTEXT
      value: "DEV"
