apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: template
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
#  ingresses:
#    - "https://sf-mellomvare.template.intern.dev.nav.no"
#  azure:
#    application:
#      enabled: true
#      allowAllUsers: true
#      tenant: trygdeetaten.no
#      claims:
#        extra:
#          - azp_name
#          - NAVident
#    sidecar:
#      enabled: false
#  accessPolicy:
#    inbound:
#      rules:
#        - application: salesforce
#          namespace: teamcrm
#          cluster: dev-external
#  envFrom:
#    - secret: template
  env:
    - name: AN_ENV
      value: "a value in dev"
